[project]
name = "hypercore-ca-distributor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic-settings>=2.10.1",
]

[tool.setuptools.packages.find]
where = ["packages"]